config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :events
  get "/filter_by_tag", to: 'events#filter_by_tag'

  get '/'=> 'events#index'
   get '/tips', to: 'pages#tips'
   get '/admin', to: 'pages#admin'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'


end

app/models/event.rb
require 'open-uri'
require 'JSON'
class Event < ActiveRecord::Base
  belongs_to :user
	has_many :event_tags
	has_many :tags, through: :event_tags

  validates :user_id, :title, :description, :datetime, :city, :state, :zip, :location,
  	:presence => true
  validates :zip, length: { is: 5 }, numericality: { only_integer: true }

  def created_by?(user)
  	return true if self.user == user
  	return false
  end

  def self.get_FB_picture_url( event_source, event_url )
    if event_source == 'Facebook'
      event_id = event_url.split( "/" )[-1]
      event_cover_obj = JSON.parse( open( "https://graph.facebook.com/v2.8/" + event_id + "?access_token=" + ENV['FB_ACCESS_TOKEN'] + "&fields=cover" ).read )

      return event_cover_obj['cover']['source']
    else
      return ""
    end
  end

end

app/models/event_tag.rb
class EventTag < ActiveRecord::Base
	belongs_to :tag
	belongs_to :event
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :event_tags
	has_many :events, through: :event_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
				 :omniauthable, :omniauth_providers => [:facebook]

	has_many :events_owned, foreign_key: "user_id", class_name: "Event"

	def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	    user.name = auth.info.name   # assuming the user model has a name
	    user.avatar_URL = auth.info.image # assuming the user model has an image
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_tags, only: [:new, :edit]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  # GET /events
  def index
    @nyevents = Event.where(approved:true).where(location: "New York, NY").where("DATE(datetime) >= ?", Date.today - 1.day).order("datetime ASC")
    @sfevents = Event.where(approved:true).where(location: "San Francisco, CA").where("DATE(datetime) >= ?", Date.today - 1.day).order("datetime ASC")
    @chievents = Event.where(approved:true).where(location: "Chicago, IL").where("DATE(datetime) >= ?", Date.today - 1.day).order("datetime ASC")
    @bosevents = Event.where(approved:true).where(location: "Boston, MA").where("DATE(datetime) >= ?", Date.today - 1.day).order("datetime ASC")
    @laevents = Event.where(approved:true).where(location: "Los Angeles, CA").where("DATE(datetime) >= ?", Date.today - 1.day).order("datetime ASC")
    @dcevents = Event.where(approved:true).where(location: "Washington, DC").where("DATE(datetime) >= ?", Date.today - 1.day).order("datetime ASC")
  end

  # GET /events/1
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    guard_against_tampering(@event)
  end

  # POST /events
  def create
    @event = Event.new(event_params)
    @event.user = current_user
    @event.picture_url = Event.get_FB_picture_url( event_params['event_source'], event_params['url'] )
    if @event.save
      EventTag.create(event_id: @event.id, tag_id: Tag.find(params[:event][:tag]).id)
      redirect_to @event, notice: 'Thank you for submitting an event! It will be reviewed by an administrator shortly.'
    else
      set_tags
      render :new
    end
  end

  # PATCH/PUT /events/1
  def update
    guard_against_tampering(@event)
    tag = Tag.find(params[:event][:tag])
    @event_tag = EventTag.find_by(event_id: @event.id)
    if @event.update(event_params) && @event_tag.update(tag_id: tag.id)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      set_tags
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    guard_against_tampering(@event)
    @event_tags = EventTag.where(event_id: @event.id)
    @event_tags.each { |event_tag| event_tag.destroy }
    @event.destroy
    redirect_to events_url, notice: "Your event, '#{@event.title}' was successfully deleted."
  end

  #Filter Events By Tags

  def filter_by_tag
    if params[:event][:tag_id] == ""
      flash[:notice] = "You must select a tag."
      redirect_to :back
    else
      tag = Tag.find(params[:event][:tag_id])
      @events = tag.events
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def set_tags
      @tags = Tag.all
    end

    # Warden method to prevent non-admins from editing content that is not their own
    def guard_against_tampering(event)
      if event.user != current_user # Must be the event's owner
        if current_user.admin? != true # or they must be a site Administrator
          redirect_to event, alert: "You are not the creator of this event or a Protest45 Admin."
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(
        :user_id,
        :title,
        :description,
        :datetime,
        :address1,
        :address2,
        :city,
        :state,
        :zip,
        :location,
        :url,
        :approved,
        :event_source)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def tips
end

def admin
  @events = Event.where(approved: false)
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
end

def create
@user = User.find_by(username: params[:sessions][:username])
  if @user && @user.authenticate(params[:sessions][:password])
    session[:user_id] = @user.id
    redirect_to root_path
  else
    flash.now[:danger] = 'Invalid email/password combination'
    render 'new'
  end
end

def destroy
  session.delete(:user_id)
  @current_user = nil
  redirect_to root_url
end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_eventlist.html.erb
 <div class="">
  <h3><%= link_to event.title, event %></h3>
  <div class="event-user-details">
    <img src="<%= event.user.avatar_URL %>" />
    <p><%= event.user.name %></p>
  </div>
  <p><%= event.datetime.strftime("%A, %B %e - %m:%M%p") %></p>
  <p><%= event.address1 %> </p>
  <p><%= event.address2 %> </p>
    <span><%= event.city %></span>,<span> <%= event.state %></span><span> <%= event.zip %> </span>
  <p>Description: <%= event.description %></p>

  <% if event.url != "" %>
    <%= link_to 'Go', event.url %>
  <% end %>
</div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <!-- For Error handling -->
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Mandatory info -->
<div class="container">
    <div class="row">
      <div class="col-sm-3">
        <%= f.label  :title %>
      </div>
      <div class="col-sm-9">
        <%= f.text_field :title %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-3">
        <%= f.label :description %>
      </div>
      <div class="col-sm-9">
        <%= f.text_area :description %>
      </div>
    </div>



    <div class="row">
      <div class="col-sm-3">
        <%= f.label :location %>
      </div>
      <div class="col-sm-9">
        <%= select_tag( 'event[location]',
              options_for_select([['Select a Location',nil],
                                  ['Washington, DC','Washington, DC'],
                                  ['New York, NY','New York, NY'],
                                  ['San Francisco, CA','San Francisco, CA'], ['Los Angeles, CA','Los Angeles, CA'],
                                  ['Boston, MA','Boston, MA'], ['Chicago, IL','Chicago, IL'] ])) %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <%= f.label "Date and Time" %>
      </div>
      <div class="col-sm-12">
        <%= f.datetime_select(:datetime, ampm: true ) %>
      </div>
    </div>

  <!-- URL -->
    <br><br>
    <div class="row">
      <div class="col-sm-3">
        <%= f.label "URL" %>
      </div>
      <div class="col-sm-9">
        <%= f.text_field :url %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-3">
        <%= f.label :event_source %>
      </div>
      <div class="col-sm-9">
        <%= select_tag( 'event[event_source]',
              options_for_select([['Facebook','Facebook'],
                                  ['Meetup.com','Meetup.com'],
                                  ['Other','Other'] ])) %>
      </div>
    </div>

  <!-- Address for Maps-->
    <br><br>
    <div class="row">
      <div class="col-sm-3">
        <%= f.label :address1 %>
      </div>
      <div class="col-sm-9">
        <%= f.text_field :address1 %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-3">
        <%= f.label :address2 %>
      </div>
      <div class="col-sm-9">
        <%= f.text_field :address2 %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-3">
        <%= f.label :city %>
      </div>
      <div class="col-sm-9">
        <%= f.text_field :city %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-3">
        <%= f.label :state %>
      </div>
      <div class="col-sm-9">
        <%= f.text_field :state %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-3">
        <%= f.label :zip %>
      </div>
      <div class="col-sm-9">
        <%= f.text_field :zip %>
      </div>
    </div>

           <div class="row">
      <div class="col-sm-3">
        <%= f.label :tag%>
      </div>
      <div class="col-sm-9">
        <select name="event[tag]" id="event_tag">
        <%@tags.each do |tag|%>
          <option value=<%=tag.id%>><%=tag.name%></option>
        <%end%>
        </select>
      </div>
    </div>



    <% if current_user.admin? %>
    <div class="row">
      <div class="col-sm-3">
         <%= f.label :approved %> <br />
        <%= f.select :approved, [['true', true], ['false', false]], :class => "browser-default"%>
      </div>
    </div>
    <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<br><br>

<small>Warning: This action cannot be undone!</small><br>
<%= button_to "Delete #{@event.title}?", event_path, method: "delete" %>

<br><br>
<%= link_to "Back to #{@event.title}", @event %> |
<%= link_to 'Back to Events', events_path %>

app/views/events/filter_by_tag.html.erb
<%if @events.length < 1 %>
  <h1>No Search Results Found!</h1>
<%else%>
<h1>Filter Results</h1>
  <%@events.each do |event|%>
    <%= render partial: "eventlist", locals: { event: event } %>
  <% end %>
<%end%>
<%=link_to "Back", events_path%>

app/views/events/index.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<p id="notice"><%= notice %></p>

<div class="container">


<%=form_tag filter_by_tag_path, method: 'get' do %>
  <p>Filter by Tag: <%=collection_select :event, :tag_id, Tag.all, :id, :name, include_blank: "Please Select a Tag"%>
    <%=submit_tag "Filter"%>
  </p>
<%end%>

<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#dc">Washington, DC</a></li>
  <li><a data-toggle="tab" href="#ny">New York, NY</a></li>
  <li><a data-toggle="tab" href="#sf">San Francisco, CA</a></li>
  <li><a data-toggle="tab" href="#la">Los Angeles, CA</a></li>
  <li><a data-toggle="tab" href="#bos">Boston, MA</a></li>
  <li><a data-toggle="tab" href="#chi">Chicago, IL</a></li>
</ul>


<div class="tab-content">
  <div id="dc" class="tab-pane fade in active">
    <h3>Washington, DC Events</h3>
     <% @dcevents.each do |event| %>
        <%= render partial: "eventlist", locals: { event: event } %>
      <% end %>
  </div>
  <div id="ny" class="tab-pane fade">
    <h3>New York City Events</h3>
      <% @nyevents.each do |event| %>
        <%= render partial: "eventlist", locals: { event: event } %>
      <% end %>
  </div>
  <div id="sf" class="tab-pane fade">
    <h3>San Francisco Events</h3>
     <% @sfevents.each do |event| %>
        <%= render partial: "eventlist", locals: { event: event } %>
      <% end %>
  </div>
  <div id="la" class="tab-pane fade">
    <h3>Los Angeles Events</h3>
     <% @laevents.each do |event| %>
        <%= render partial: "eventlist", locals: { event: event } %>
      <% end %>
  </div>
  <div id="bos" class="tab-pane fade">
    <h3>Boston Events</h3>
     <% @bosevents.each do |event| %>
        <%= render partial: "eventlist", locals: { event: event } %>
      <% end %>
  </div>
  <div id="chi" class="tab-pane fade">
    <h3>Chicago Events</h3>
     <% @chievents.each do |event| %>
        <%= render partial: "eventlist", locals: { event: event } %>
      <% end %>
  </div>
</div>


<br>

<%= link_to 'New Event', new_event_path %>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<% if @event.picture_url != "" %>
  <img src=<%= @event.picture_url %> />
<% else %>
  <!-- add default icon here-->
  <p></p>
<% end %>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.datetime.strftime("%A, %B %e - %m:%M%p") %>
</p>

<p>
  <strong>Link:</strong>
  <%= @event.url %>
</p>

<% if current_user && current_user.admin? %>
  <p>
    <strong>approved:</strong>
    <%= @event.approved %>
  </p>
<% end %>

<p>
  <strong>Event Creator:</strong>
  <%if @event.user.name%>
    <%= @event.user.name %>
  <%else%>
    No Name Provided
  <%end%>
</p>

<p>
  <strong>Event Tags:</strong>
  <%@event.tags.each do |tag|%>
    <%=tag.name%>
  <%end%>
</p>

<% if current_user && (@event.created_by?(current_user) || current_user.admin?) %>
<%= link_to 'Edit', edit_event_path(@event) %> |
<% end %>
<%= link_to 'Home', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Protest45</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<script src="https://use.fontawesome.com/d98f023a4d.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

  <%= csrf_meta_tags %>
</head>
<body>

      <nav class="navbar navbar-default homenav">
    <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar top-bar"></span>
            <span class="icon-bar middle-bar"></span>
            <span class="icon-bar bottom-bar"></span>
          </button>
          <li id="logo"><a class="navbar-brand" href="/"><span id="logo-primary">protest</span><span id="logo-secondary">45</span></a></li>
         </div><!--navbar-header-->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav nav-det">

          <% if user_session %>
          <li class="active"><a href="/events/new"><i class="fa fa-plus-circle" aria-hidden="true"></i> Post a New Event</a></li>
          <li><%=link_to "Tips for Attending Protests", tips_path%></li>
          <li><a href="/users/sign_out">Sign Out</a></li>
            <% else %>
          <li><a href="/users/sign_up">Register</a></li>
          <li><a href="/users/sign_in">Sign In</a></li>
          <% end %>
        </ul>
      </div><!--collapse-->

    </div><!--container-->
  </nav>


<%= yield %>

<footer>

	<% if current_user %>
		<p>You are logged in as <%= current_user.email %></p>

	<% end %>
</footer>
</body>
</html>

app/views/pages/admin.html.erb
<h1> Unapproved Events </h1>
<% @events.each do |event| %>
 <div class="">
  <h3><%= link_to event.title, event %></h3>

<% end %>
</div>

app/views/pages/tips.html.erb
<div class="container">
  <div class="tips">
<h1>Tips for Protesting</h1>


<h2>1. Do Your Research</h2>
<p>Make sure you know about the issue(s) you are demonstrating for. It is important for you to be able to speak intelligently and respond to questions from the press – you might be a representative for the issue you are there for so it is important to be informed.</p>


<h2>2. What to Bring/How To Dress</h2>
<p>Pack the absolute minimum you need to a protest, as you don’t want to bring fragile and valuables (i.e. laptop) to a protest unless you are a journalist, photographer, etc. and you need to. Make sure to wear comfortable shoes and multiple layers of clothing that cover your skin so that you can be comfortable in any temperature. Beware of pickpockets at a protest, so keep your wallet and valuables in a place in your backpack that is hard to access.Certain things that might be good to include in your backpack are: </p>
<ul>
  <li>Identification</li>
  <li>Phone battery and charger</li>
  <li>Water</li>
  <li>Snacks</li>
  <li>Mini first aid kit</li>
  <li>Any medication that you can’t do without</li>
  <li>Dry Bandana</li>
  <li>Bandana soaked in vinegar, sealed in a plastic bag (in case of tear gas)</li>
  <li>Wet Wipes</li>
  <li>Pen and Paper</li>
</ul>

<h2>3.  GO WITH A GROUP</h2>
<p>DO NOT EVER GO ALONE. Go with a group or AT LEAST one other person so you can be accountable for one another and advocate for each other if there is any trouble.</p>

<h2>4. KNOW WHEN TO LEAVE</h2>
<p>More often than not, well-organized demonstrations remain peaceful. However, if you see any violence or behavior you disagree with, you should leave immediately because you might be culpable for what happens if you are part of the group. Look at the demonstration route/location(s) beforehand and plan several exit strategies so you are prepared.</p>


<h2>5. KNOW YOUR RIGHTS</h2>
<p>If you the police try to search you:</p>

<ul>
  <li>You can stay silent – you do not have to say anything</li>
  <li>You do not have to give consent – you can say no (politely) and ask them to come back with a warrant</li>
  <li>If you agree to a search, then they can search your things (including your electronic devices) without a warrant.</li>
  <li>If they do have a search warrant, ask to see it (you have the right to see it), and make sure they only search things that the warrant authorizes them to search</li>
  <li>You do not have to help them search, and you can stay silent. This includes giving them passwords or encryption keys</li>
  <li>If you have given them consent/they have a search warrant – do not obstruct their search</li>
  <li>If you have access to a lawyer, it is recommended to speak to them before any search or discussion with the police.</li>
</ul>


<h2>6. IF YOU HAVE TO INTERACT WITH LAW ENFORCEMENT</h2>
<p>If you have any conversations with the police or other law enforcement, make sure you are respectful and calm, even if you are addressing something they are doing that you disagree with. It is important to try and de-escalate any tense situation, especially with law enforcement and maintaining a calm and rational tone is one of the best ways to do so. Do not antagonize or argue with the police, it could cause trouble for other protesters and perhaps the entire protest.</p>


<h2>7. IF YOU GET ARRESTED</h2>
<p>Number one – do NOT resist arrest, even if you know or feel you have done nothing wrong. Make sure to de-escalate the situation as best as you can by being overly polite and follow their instructions (within reason) without resisting.</p>


<p>You have the right to: remain silent, and be informed of any charges against you (any their penalties), speak to your attorney (or be appointed one if you can’t afford one), and have a judge decide whether or not you should be let out of jail until your trial. The only time you do not have the right to remain silent is when they ask for your basic information like name and address.</p>

<p>Don’t resist arrest. If you’ve done nothing wrong, don’t struggle. Be overly polite and make sure the officers know your name. Do whatever you can to humanize yourself and the group you’re with. Generally police are just trying to keep everyone safe, as long as you do everything you can to show you’re not a threat, you’ll be fine. Remaining silent might be used against you later, but you can say you do not want to answer any questions without your attorney present. They are technically now allowed to question you without your lawyer present if you ask for it (unless you waive that right).</p>


<p>A good resource for a lawyer is the National Lawyers Guild – they are often at protests (you can identify them at demonstrations by their neon green hats). https://www.nlg.org/</p>
</div>
</div>